# file intended to only be used for local dev and/or test, not docker swarm use
services:
  backend-api:
    build:
      context: ../
      dockerfile: infra/backend.Dockerfile
    image: cazlo/tailored-resume-assistant-backend:latest
    # note only would use latest tag for local dev
    command:
      ["poetry", "run", "uvicorn", "tailored_resume_assistant_backend.main:app", "--workers", "8", "--host", "0.0.0.0"]
    ports:
      - 8042:8000
    depends_on:
      - task-db
  backend-queue-worker:
    build:
      context: ../
      dockerfile: infra/backend.Dockerfile
    image: cazlo/tailored-resume-assistant-backend
    command:
      "poetry run celery -A tailored_resume_assistant_backend.tasks worker --loglevel=info"
    depends_on:
      - task-db
      - task-queue
  task-queue:
    image: rabbitmq:3.13-management
    # note 3.13 selected to align with recommended version for AWS managed mq. see also https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-version-management.html
    ports:
      - 15672:15672 # management UI exposed to facilitate debug
  task-db:
    image: postgres:16.4-alpine
    # note 16.4 chosen to align  with latest available AWS RDS versions
    ports:
      - 5432:5432 # expose port only to facilitate debug
    environment:
      POSTGRES_PASSWORD: password
  frontend:
    build:
      context: ../
      dockerfile: infra/frontend.Dockerfile
    image: cazlo/tailored-resume-assistant-frontend:latest
    # note only would use latest tag for local dev
    ports:
      - 8842:80

