# file intended to only be used for local dev and/or test, not docker swarm use
services:
  backend-api:
    build:
      context: ../
      dockerfile: infra/backend.Dockerfile
    image: cazlo/tailored-resume-assistant-backend:latest
    # note only would use latest tag for local dev
    command:
      ["poetry", "run", "uvicorn", "tailored_resume_assistant_backend.main:app", "--workers", "8", "--host", "0.0.0.0"]
    ports:
      - 8042:8000
  backend-queue-worker:
    build:
      context: ../
      dockerfile: infra/backend.Dockerfile
    image: cazlo/tailored-resume-assistant-backend
    command:
      "echo 'todo celery worker command goes here'"
  task-queue:
    image: rabbitmq:3.13-management
    # note 3.13 selected to align with recommended version for AWS managed mq. see also https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-version-management.html
    ports:
      - 15672:15672 # management UI exposed to facilitate debug
  task-db:
    image: postgres:16.4-alpine
    # note 16.4 chosen to align  with latest available AWS RDS versions
    ports:
      - 5432:5432 # expose port only to facilitate debug
    environment:
      POSTGRES_PASSWORD: password
  frontend:
    build:
      context: ../
      dockerfile: infra/frontend.Dockerfile
    image: cazlo/tailored-resume-assistant-frontend:latest
    # note only would use latest tag for local dev
    ports:
      - 8842:80

  ####  GL accelerated runtimes
  mesa-gl-default-docker:
    image: cazlo/tailored-resume-assistant-llm:latest
    profiles:
      - template
    build:
      context: ..
      dockerfile: infra/amdgpu-llm.Dockerfile
      target: gpu-setup-smokecheck
    devices:
      - "/dev/kfd:/dev/kfd:rwm"
      - "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
      - "${CARD_NUMBER:-card1}:${CARD_NUMBER:-card1}:rwm"
    tty: true
    command:
      - /bin/bash
#    user: "1000:1000"
    group_add:
      - video
      - render
      - ${VIDEO_GROUP_NUMBER:-1}
      - ${RENDER_GROUP_NUMBER:-2}

  # note: this is intended to only be used when in the docker "rootless" context
  # not the "default" context, which is root-full
  mesa-gl-rootless-docker:
    image: cazlo/tailored-resume-assistant-llm:latest
    profiles:
      - template
    build:
      context: ..
      dockerfile: infra/amdgpu-llm.Dockerfile
      target: gpu-setup-smokecheck
    devices:
      - "/dev/kfd:/dev/kfd:rwm"
      - "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
      - "${CARD_NUMBER:-card1}:${CARD_NUMBER:-card1}:rwm"
    tty: true
#    entrypoint:
#      -  /bin/bash
#    command:
#      - /bin/sh
#    user: "ubuntu"
    ipc: host # todo may not be needed
    shm_size: 8GB
    cap_add:
      - SYS_PTRACE
#    privileged: true
#    group_add:
#      - daemon
#      - 106
#      - 235
#      - daemon
#      - video
#      - render
#      - ${VIDEO_GROUP_NUMBER:-1}
#      - ${RENDER_GROUP_NUMBER:-2}
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./data:/data
    environment:
      HUGGINGFACE_HUB_CACHE: /data

  gpu-setup-smokecheck:
    extends:
      service: mesa-gl-rootless-docker